### ISSUE TITLE
Create a list of the the exercises

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#1]
We can start from http://senecajs.org/getting-started.html for a basic skeleton

**Comment by mcdonnelldean** [comment]
@marcopiraccini Lets talk on this, I've been talking to richard about this page and possibly adding more meat here which would dovetail well with this. I think Glen Keane is doing some things here too.

**Comment by mcdonnelldean** [comment]
@marcopiraccini @piccoloaiutante Is there a sample workshopper that I could look at so I know what a complete one should look like?

**Comment by piccoloaiutante** [comment]
I suggest you to have a look at learnyounode (https://github.com/workshopper/learnyounode)

**Comment by marcopiraccini** [comment]
Yes, in any case, see the ones that uses the `workshopper` module. The `problems` structure is already done, so simply start doing the problem implementation

**Comment by marcopiraccini** [comment]
And -of course- also, @thekemkid can help :)

**Comment by piccoloaiutante** [comment]
We should first agree on the list of the thing that we want to teach in this workshop

**Comment by mcdonnelldean** [comment]
Cheers all. I just wanted to go through one before I started to help to make sure I understand the structure. I presume they are all pretty standard. Yes let's get a list start. I think some of the main points to cover are
- Pattern matching
- Transports
- Storage
- Seneca server to server comms
- Browser / Rest communication via REST.

We need to break them down further but these are the main things that I feel you need to know to get a good handle on seneca.

**Comment by piccoloaiutante** [comment]
For the first workshop i would go for pattern matching, storage and rest communication. consider that it will be an introduction....

**Comment by mcdonnelldean** [comment]
I agree, you will need to add a storage in there to be complete. JSON File store is a lovely way to have storage without having to explain database stuff? Thoughts?

**Comment by marcopiraccini** [comment]
I agree on the list, but it's top-level and must be further detailed (the problems must be progressive). 
This is the draft of the problem list shared in the doc (mainly follow the Seneca getting started): 
- 1.sum: create server for 2 num sums 
- 2.client:create client to consume it
- 3.roles: pattern matching with role and command
- 4.extend: extend pattern with another pattern
- 5.extend-client: extend client with second pattern call
- 6.multiple: multiple extended pattern (the one with integer true) 
- 7.override: override a pattern
- 8.transport: move the different pattern to another seneca instance unsing seneca-transport
- 9.more-transport: Add different trasport
- 10.mem-store: saving and retrieving something with seneca-mem-store
- 11.plugin: Write a seneca plug-in
- 12.web: adding seneca-web?

So it's probably more practical to start modifying this list.

**Comment by GlenTiki** [comment]
A client-server hello world should be the first exercise.
Then basic maths.
Then pattern matching extending that maths stuff.

Then pretty much @marcopiraccini's plan, I think

**Comment by marcopiraccini** [comment]
Yes, @thekemkid, but remember that in nodeSchool exercises you usually write one "part", so you write the serve or the client, that's because the verifier will verify the server with a client, and the opposite. 
If we write a problem that to be solved needs the server AND the client, it's difficult to verify it automatically (I think).

**Comment by mcdonnelldean** [comment]
Looking good @marcopiraccini.

**Comment by GlenTiki** [comment]
Should we create seperate issues for each exercise and assign them out/self assign them?

**Comment by mcdonnelldean** [comment]
@thekemkid I think that would be a good idea. Talk to @marcopiraccini today and get the process kicked off :+1:

**Comment by marcopiraccini** [comment]
Talking with @mcollina during the return trip, we agreed that it's probably better to introduce the concept of seneca "plugin" ASAP in the exercises. So that: 
- In the first exercise we make write one service, but with no seneca initialization (the verifier will require the "sum" service to test it. 
- In the second exercise we introduce the plugin structure.

So my proposal is: 

```
1.sum: create service for 2 num sums
2.plugin: create the plugin for the "sum"
3.client:create client to consume the "sum"
4.roles: pattern matching with role and command
5.extend: extend pattern with another pattern
6.extend-client: extend client with second pattern call
7.multiple: multiple extended pattern (the one with integer true)
8.override: override a pattern
9.transport: move the different pattern to another seneca instance unsing seneca-transport
10.more-transport: Add different trasport
11.mem-store: saving and retrieving something with seneca-mem-store
12.web: adding seneca-web?
```

**Comment by mcdonnelldean** [comment]
I would agree with the above, it looks like a solid list.

**Comment by mcdonnelldean** [comment]
If you break em out into issues we could tackle them one at a time.

**Comment by piccoloaiutante** [comment]
I'm not so convinced by the 12th step: what would you like to see in "Write a seneca plug-in" ?

**Comment by marcopiraccini** [comment]
It was a copy&paste mistake, fixed. Following this hypotesis, plugins are introduced in the second exercise.

**Comment by marcopiraccini** [comment]
@mcdonnelldean Yes, I would like first to create the "sum" exercise to be used as a blueprint for the others.

**Comment by mcollina** [comment]
:+1: for the discussed list!

**Comment by piccoloaiutante** [comment]
@marcopiraccini in that case :+1:  :smile:
