### ISSUE TITLE
plugin wont work. i'm tring use real seneca and it's worked fine.

### ISSUE THREAD

**Issue by dima1034** [senecajs/seneca-in-practice#103]
so please try to fix it.  cose some of the people will frustrate about that

**Comment by piccoloaiutante** [comment]
Hi @dima1034,

could you please give some more info about what's not working and the error that you got?

**Comment by dima1034** [comment]
as I mentioned before with regular seneca everything works pretty well.

![image](https://cloud.githubusercontent.com/assets/13873676/25848050/5b4c0fb0-34c1-11e7-93a3-08bf6db1263b.png)

![image](https://cloud.githubusercontent.com/assets/13873676/25848133/a0d662a6-34c1-11e7-8101-15e5de994e53.png)

**Comment by marcopiraccini** [comment]
Hi @dima1034. Which Seneca version are you using? 
Can you please paste here your solution so we can check?

**Comment by dima1034** [comment]
http://dropmefiles.com/qPJhz
