### ISSUE TITLE
Passing

### ISSUE THREAD

**Issue by code-jace** [senecajs/seneca-in-practice#11]
checked 5-8 will pass regardless of file verified (used a blank.js) and only give a PASS reply - no feedback or official solution.

**Comment by piccoloaiutante** [comment]
Hi @code-jace,

i'm going to check it, thx

**Comment by piccoloaiutante** [comment]
it should be fixed. is it still happening to you? @code-jace

**Comment by code-jace** [comment]
is the update available?

**Comment by piccoloaiutante** [comment]
i pushed code yesterday, btw i just found a similar problem for the sum exercise and i'm fixing it :-(

**Comment by marcopiraccini** [comment]
@code-jace: can yoo check if fixed?

**Comment by code-jace** [comment]
np
