### ISSUE TITLE
Upgrade to Seneca 1.0

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#21]

**Comment by piccoloaiutante** [comment]
do you need help? :-) i'm going to test it tomorrow morning..

**Comment by marcopiraccini** [comment]
Sure I need help :)

**Comment by piccoloaiutante** [comment]
I tested it this morning with seneca 1.0.0. I was able to accomplish all the tasks. How about you @marcopiraccini ?

**Comment by marcopiraccini** [comment]
Tested also with seneca 1.2! :)
