### ISSUE TITLE
Solutions and Sample code not being tested

### ISSUE THREAD

**Issue by CodeWriterWriter** [senecajs/seneca-in-practice#22]
Seneca-in-practice is throwing this error on commands 
- `seneca-in-practice verify <filename>`
- `seneca-in-practice run <filename>`

```
Error: Cannot find module '/Users/isaacmahon/Documents/senecaInPractice/problems/extend/seneca-extend-executor.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

As a result it's comparing the lack of output from not being able to run the sample code, with the lack of output from not being able to run the user code, seeing they're equivalent, and passing the user on every challenge regardless of what user code is given, including blank files.
Tested on two separate machines and error exists on both.
Seneca-in-practice version 0.1.8 
Node version 4.2.4

**Comment by marcopiraccini** [comment]
It's clearly looking for the executor in the wrong place. Anyone using OS X can check it?

**Comment by piccoloaiutante** [comment]
i will do today or tomorrow

**Comment by evannieuwburg** [comment]
I'm on OSX and get the same issue:

EriNie@hes500320  ~/Developer/seneca-school  seneca-in-practice run program.js
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/EriNie/Developer/seneca-school/problems/sum/seneca-sum-executor.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by piccoloaiutante** [comment]
That should be fixed in this PR 

https://github.com/senecajs/seneca-in-practice/pull/24

@marcopiraccini how about it?

**Comment by marcopiraccini** [comment]
I can confirm that is fixed

**Comment by evannieuwburg** [comment]
Also confirmed. It's been fixed.

**Comment by piccoloaiutante** [comment]
thanks @evannieuwburg :+1:

**Comment by sagar021988** [comment]
I am new to protractor and i have configured protractor on eclipse luna on windows 10 and while running the protractor test case via eclipse i am facing error as 👍

module.js:340
throw err;
^

Error: Cannot find module 'C:\Users\Sagar'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:289:25)
at Function.Module.runMain (module.js:467:10)
at startup (node.js:136:18)
at node.js:963:3

Can you please help me in debugging the same with complete solution step by step as i need this urgently .

Thanks in advance for your co operation
