### ISSUE TITLE
Fuge step

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#23]
It should be great to have one (final?) step explaining how to use Fuge (https://github.com/apparatus/fuge) for generating execution environment.

**Comment by piccoloaiutante** [comment]
I would avoid to do it here since the focus here is on seneca itself. Adding that step to seems a little bit out of scope.

**Comment by piccoloaiutante** [comment]
so what's your thought about it @marcopiraccini ?

**Comment by marcopiraccini** [comment]
Well, I'd still like to have a "final" step with it, to show how "real" microservices can be created, but we have to figure out how that can be verified. 
Maybe we simply describe how to create it and simply verify from the client point-of-view (assuming that if it works, the service has been created with fuge).

**Comment by batjko** [comment]
I agree with @piccoloaiutante. Fuge is just one possible implementation that uses Seneca. There is no reason to make it look like it's part of Seneca. 
Adding a Fuge step would be like... adding React to a Javascript tutorial, if you know what I mean.
