### ISSUE TITLE
sum - extend the executor to support seneca execution

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#3]
Now the verify mechanism for the "sum" exercise is quite raw: both the solution and the submitted .js are passed as parameter to a `seneca-xxx-executor`, and then the stdouts are compared.
This mechanism works, however it is better (and much more elegant) to extend the workshopper executor to support this cases. 
This mechanism will also use for the exercises that use the seneca plugin.

**Comment by mcdonnelldean** [comment]
How do I run it locally marco? As in from the repo :D

**Comment by marcopiraccini** [comment]
`node runners.js`
`node runners.js verify my_solution.js`
`node runners.js run my_solution.js`

**Comment by mcdonnelldean** [comment]
Awesome, I'll take a peek for you tonight.

**Comment by piccoloaiutante** [comment]
Me too @mcdonnelldean. should i go for the second step or lets work on this one and then move?

**Comment by mcdonnelldean** [comment]
@piccoloaiutante Check with @marcopiraccini I only have my feet half in right now while I try hand off Seneca stuff to Wyatt :dancer:

**Comment by marcopiraccini** [comment]
@mcdonnelldean @piccoloaiutante try the first one and look/review the code and the exercise. Then, decide by yourself if do some work on the "sum" exercise or go on with others. Also think about the object of this issue. In any case, write on gitter what are you working on to avoid overlap.

**Comment by marcopiraccini** [comment]
No more actual
