### ISSUE TITLE
Change text from 'action' to 'cmd' in Ex1: Sum

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#30]
A minor tweak, but it tripped me up... the first line in Ex1: Sum says:

"Build a simple seneca service for the role math and **action** sum."

But the solution requires role:math, **cmd**:sum

I suggest changing or clarifying the instruction

**Comment by piccoloaiutante** [comment]
fixed with this commit

https://github.com/senecajs/seneca-in-practice/commit/b8916659975926a4bf74a5847f2d70912bac3073

**Comment by piccoloaiutante** [comment]
how is it @irelandm ?

**Comment by irelandm** [comment]
This is better, as someone would be more likely to make the link between 'command' and 'cmd', especially with the example just above. It would be even better also to state the pattern to be added though, i.e. role:math, cmd:sum.

**Comment by marcopiraccini** [comment]
@irelandm please check if this it's OK https://github.com/senecajs/seneca-in-practice/blob/pre-jsday/problems/sum/problem.md

**Comment by irelandm** [comment]
Yes, that looks fine now.

_Mark Ireland_
Architect

[image: Nearform.com] http://www.nearform.com/

+353 87 451 6354 (mobile)
mark.ireland_6 (skype)
mark.ireland@nearform.com
www.nearform.com

Transforming the way Enterprise is building Software

Blog: Nodecrunch http://www.nearform.com/nodecrunch     Open source:
Seneca http://www.senecajs.org/ | Fuge https://github.com/apparatus/fuge
 | Hapi http://hapijs.com/ | nScale http://nscale.nearform.com/
