### ISSUE TITLE
Remove references to plugin from Ex2: Client

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#31]
The Client exercise makes reference to plugins, as if the plugin exercise had already been completed, but it hasn't at that point.

Suggest editing the first line of the exercise description and also removing the references to **seneca.use**, which will cause errors if put in the code

**Comment by piccoloaiutante** [comment]
done

**Comment by conolan** [comment]
There are other issues that cause confusion for newbies.
'role:greetings,cmd:hello' isn't a json object, and it's too early to be using shorthand stuff I think.
Also, there is no reference to seneca.act in the example.
The reference to 'action sum' will cause confusion. It's OK to use action (or any other term) but they will cause the exercise to fail.

**Comment by conolan** [comment]
OK, I see we don't need seneca.act because it's in the executor.

**Comment by marcopiraccini** [comment]
That should fix this also: https://github.com/senecajs/seneca-in-practice/pull/42
