### ISSUE TITLE
Fix execution script for Ex2: Client

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#33]
For the Client exercise, when executed as:

> seneca-in-practice run client.js

The response is:

> { answer: NaN }

This is because the query parameters are not numbers. There is a bug in the exercise.js script whereby process.argv[3], process.argv[4] are passed for the run operation instead of numbers (as per the verify operation)

**Comment by irelandm** [comment]
Also it isn't clear to me why the params are passed in arguments 3 and 4, rather than 2 and 3

**Comment by irelandm** [comment]
This also affects ex 6: Extend Client

**Comment by piccoloaiutante** [comment]
@irelandm   did you run this from github code or from npm?

**Comment by piccoloaiutante** [comment]
arguments are 3 and 4 because if you run `seneca-in-practice run client.js` this are args[0],args[1],args[2]

**Comment by irelandm** [comment]
I ran this from npm

**Comment by conolan** [comment]
I find it very confusing that the plugin is introduced, when we don't learn about plugins until the next problem.

This statement throws a new user into chaos, because they haven't organised it into a plugin.

> We know how to create a Seneca Microservice and how to organize it in a Seneca
> plugin.

**Comment by irelandm** [comment]
Conor - you're right about the plugin, but take a look at the next issue below - it has now been fixed

**Comment by conolan** [comment]
I've replicated the NaN problem. 
If I run 
`node program 1 2 3`
I get answer: 5, so it works, but not in seneca-in-practice

**Comment by marcopiraccini** [comment]
That should fix this issue: https://github.com/senecajs/seneca-in-practice/pull/42 
@piccoloaiutante can you please review?
