### ISSUE TITLE
Make it clear how many calls are needed and in what order in Ex 6: Extend Client

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#34]
The instructions for Ex 6: Extend Client state:

`extend the client of the sum plugin so that it call the two plugins that we previously developed`

It would be more helpful if it was clearer which messages were needed and in what order, otherwise it is trial and error to get the solution verified. Also, the reference to **two** plugins is confusing, as I had only developed **one**, supporting multiple message types.

**Comment by piccoloaiutante** [comment]
How does it sound this to you @irelandm :

`The goal of the exercise is to extend the client that we developed,
so that it calls the two patterns that we created at previous step.`

**Comment by irelandm** [comment]
Sounds good. If the order of the calls is significant to getting the exercise validated, then I'd add that to the instructions too.

**Comment by piccoloaiutante** [comment]
No the order doesn't matter for this exercise.

**Comment by marcopiraccini** [comment]
@piccoloaiutante: not true. The order count! This make the validation fail: 

```
'use strict'

var seneca = require('seneca')

const left = Number(process.argv[2])
const right = Number(process.argv[3])

seneca.use('./math_ex6')
  .act({
    role: 'math',
    cmd: 'sum',
    integer: true,
    left: process.argv[2],
    right: process.argv[3]
  }, (err, result) => {
    if (err) return console.error(err)
    console.log(result)
  })
  .act({role: 'math', cmd: 'sum', left, right}, function (err, result) {
    if (err) return console.error(err)
    console.log(result)
  })
```
