### ISSUE TITLE
Not clear why it is an override in Ex 7: Override 

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#35]
The ex 7: Override instructions state:

```
The patterns resolve using the following rules:

  * More properties win.
  * If the patterns have the same number of properties, they are matched in alphabetical order.
```

However the example given seems to have the same message signature twice and relies on the overriding action being defined last. So this is a third rule. If this is the case then please add. Otherwise, please explain how the override works.

This is also the same for the example on http://senecajs.org/get-started/

**Comment by marcopiraccini** [comment]
@irelandm is the current description clearer?

**Comment by marcopiraccini** [comment]
Tested with a class, the description seems to be unclear yet. We have to review it.
