### ISSUE TITLE
Use plugin format for the example in Ex7: override

### ISSUE THREAD

**Issue by irelandm** [senecajs/seneca-in-practice#36]
The example doesn't work as-is and would be better in plug-in format

**Comment by conolan** [comment]
The example in problem.md if run, shows no difference in output whether the first action or second action (with prior) is run. Both give same output when I use this  .act

```
seneca.act({role:'greetings',cmd:'hello', name:'paddy'},function (err, result) {
  if (err) return console.error(err)
  console.log(result)
})
```

Suggest changing the example to this, which will output differently depending on which is run.

```
var nameSize=0

seneca.add( 'role:greetings, cmd:hello', function( msg, respond ) {
    var hello = "Hello " + msg.name;
    respond( null, { answer: hello });
});

seneca.add( 'role:greetings, cmd:hello', function( msg, respond ) {
  nameSize=msg.name.length;
   // call previous action function for role:greetings,cmd:hello
   this.prior({
     role:  'greetings',
     cmd:   'hello',
     name:  msg.name
   }, function( err, result ) {
     if( err ) return respond( err )

     respond( null, { answer: result.answer + nameSize});
   })
});
```

The solution assumes that the action that runs will have a math.floor for each argument. I suggest you add this line.

> The action that runs with finite numbers should round the numbers down.

**Comment by piccoloaiutante** [comment]
We added a `info` property in prior callback so that you can understand if you call has passed through prior. Is it clearer now?
