### ISSUE TITLE
[Ex 11 - Mem Store] Outdated instructions - New way to use data entity functions

### ISSUE THREAD

**Issue by adrianmcli** [senecajs/seneca-in-practice#41]
Since Seneca has been updated, you won't be able to make use of any of the data entity stuff unless you install the separate package.
1. Install the package:
   
   ```
   npm install --save seneca-entity
   ```
2. Activate it:
   
   ``` js
   seneca.use('entity')
   ```
3. Now you can use it:
   
   ``` js
   var op = seneca.make('operation')
   ```

Reference: https://github.com/senecajs/seneca/issues/383

**Comment by marcopiraccini** [comment]
Specified in: https://github.com/senecajs/seneca-in-practice/pull/42

**Comment by marcopiraccini** [comment]
Merged in Released 0.1.14, can you please check if it's OK?

**Comment by adrianmcli** [comment]
@marcopiraccini np, thanks for the fix, I'll report back soon.

**Comment by adrianmcli** [comment]
@marcopiraccini Excellent, it works! I especially enjoy the MUCH PROFIT screen haha.

**Comment by adrianmcli** [comment]
@marcopiraccini I noticed a few grammar mistakes in the English. Perhaps I'll make a PR!

**Comment by marcopiraccini** [comment]
Yes please :)
