### ISSUE TITLE
 Ex7: Override - check solution 

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#44]
After a class: the expected solution seems not to be "incremental" (the `integer:true` pattern from previous extension should be used?) Clarify that.

**Comment by piccoloaiutante** [comment]
Should we remove the integer true for the runner? 

https://github.com/senecajs/seneca-in-practice/blob/master/problems/override/seneca-override-executor-run.js#L9

**Comment by marcopiraccini** [comment]
Already done (but not for the "run" executor :D) : https://github.com/senecajs/seneca-in-practice/commit/cecbaac223f3e4119a491f836dc0996e86058cb4 
...but I think all the exercise should be reviewed

**Comment by batjko** [comment]
This was confusing for me as well. I then noticed in the solution that the `integer:true` option wasn't even present anymore. Some clarification here would be nice.
