### ISSUE TITLE
Ex 9 (Transport): Port not recognized

### ISSUE THREAD

**Issue by batjko** [senecajs/seneca-in-practice#48]
Hi guys,

I'm pretty sure I am giving it the right thing, but I keep getting an error from Seneca that the port is NaN:

``` bash
Seneca Fatal Error
==================

Message: seneca: gate-executor: "port" argument must be >= 0 and < 65536

Code: transport_listen

Details: { port: NaN,
  host: '127.0.0.1',
  type: 'web',
  path: undefined,

etc.
```

Here's my code:

``` js
const seneca = require('seneca')()
const math = require('./math-plugin')
seneca.use(math).listen(process.argv[2], '127.0.0.1')
```

If I start it manually with `node math-service.js 8080`, I get a working Seneca service, though:
![Imgur](http://i.imgur.com/E0t3OvZ.png)

So I can only assume it's an issue with verify and the context of my environment maybe?
I also tried converting `process.argv[2]` into a number first, but the error is the same.
This is on Windows 7 btw, with Node 6.2.

Suggestions?

**Comment by sndwch** [comment]
👍  

Same on OSX.

**Comment by kanaqsasak** [comment]
:+1:

Same on Ubuntu

**Comment by marcopiraccini** [comment]
Should be fixed in https://github.com/senecajs/seneca-in-practice/pull/54 We will check it when merged

**Comment by marcopiraccini** [comment]
Now that should be fixed, but I can test it only with Ubuntu. Needed help to test with OSx and (especially) Windows

**Comment by batjko** [comment]
I don't have it installed on my Windows machine anymore. Is there any quick way to run Step 9 without having to go through all the previous ones again?

**Comment by piccoloaiutante** [comment]
@batjko you should be able to select it directly from the menu. Once selected the workshop should run that step.

**Comment by batjko** [comment]
I'll confirm when I'm back on my Windows machine later today.

**Comment by batjko** [comment]
So uh... here is what I get now:
```bash
PS C:\git\sip> seneca-in-practice verify index.js
Invoking sum with random generated: 31, 99:
{"kind":"notice","notice":"seneca started","level":"info","when":1475089557861}
PS C:\git\sip>
```

So no error, some seemingly meaningful output, but no verify from seneca-in-practice.

**Comment by batjko** [comment]
So I tried and don't get an error, but now I can't get verification to run:

``` shell
PS C:\git\sip> seneca-in-practice verify index.js
Invoking sum with random generated: 37, 45:
PS C:\git\sip>
```

Even tried the exact solution from this repo.

**Comment by marcopiraccini** [comment]
Tnx @batjko , the problem was that in win, apparently, `seneca.listen()` take a long time to start. Augmenting the timeout before trying to connect to 5000 millis seems to have fixed the issue (see: https://github.com/senecajs/seneca-in-practice/pull/65).

If you have time to verify, it would be great :)

**Comment by batjko** [comment]
It doesn't wait 5000 millis, I'm afraid. Just about 1 second. Did you push the update?

``` shell
PS C:\git\sip> seneca-in-practice verify index.js
  Invoking sum with random generated: 11, 55:
  {"kind":"notice","notice":"seneca started","level":"info","when":1475333257895}
PS C:\git\sip>
```

I even uninstalled and re-installed the seneca-in-practice package, no luck.

**Comment by marcopiraccini** [comment]
@batjko probably the issue was still there becaues I forgot to do a release :(. Can you please check again updating the version?

**Comment by batjko** [comment]
Yup, works now on Windows.
It took between 3 and 4 seconds, to move on, which is odd but the 5 sec timeout definitely seems to have solved it.
