### ISSUE TITLE
Add exercise on `use`, `ready` and plugin order 

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#57]
We don't have an exercise that explain `use`, `ready` and plugin order. 
We should explain something like: 
https://github.com/senecajs/seneca/blob/master/docs/examples/load-order.js

**Comment by piccoloaiutante** [comment]
https://github.com/senecajs/seneca-in-practice/pull/82

**Comment by piccoloaiutante** [comment]
https://github.com/senecajs/seneca-in-practice/pull/83
