### ISSUE TITLE
general problems in exercises

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/seneca-in-practice#61]
@marcopiraccini asked me to test the exercises... unfortunately I'm proceeding quite slowly but here's a number of initial findings on the first two exercises:
## sum

1- It's not explained that the expected response should be in the {answer:sum} format. As first test I was just returning sum and the error message wasn't helpful 
## client

1- It's not clear if you need to write on the console `result` or `result.answer`
2- My default seneca installation emits many logs on boot and on action and the verifier uses the first line to check for correctness, always resulting in a failure. Possible solutions: indicate to use the `log:silent` option, pass it in as a command line option (IIRC `--seneca.log=silent`), or use the last log line instead of the first one
3- May be not completely clear what is happening with the renaming to math.js and the require, I think it would be better to explain that we are reusing the seneca instance from previous exercise (also, what if the user doesn't follow the exercises linearly?)

**Comment by marcopiraccini** [comment]
"2- My default seneca installation emits many logs on boot and on action and the verifier uses the first line to check for correctness, always resulting in a failure. " -> This is a bug, the verifier should skip seneca logs.

**Comment by paolochiodi** [comment]
maybe there have been changes in the logger on seneca 3.1 or 3.2?
(I'm using node 6, seneca 3.2.1)

Exercise output:

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "{\"kind\":\"notice\",\"notice\":\"seneca started\",\"level\":\"info\",\"when\":1475050453934}" !=    "{ answer: 121 }"

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to Client didn't pass. Try again!
```

**Comment by paolochiodi** [comment]
According to https://github.com/senecajs/seneca-in-practice/blob/master/problems/comparestdout-filterlogs.js#L17 the problem may be that the new log message doesn't have a `seneca` attribute.

I think it could be dropped, or substituted with the `kind` attribute. Even better for retro-compatibility to check if one of `kind` or `seneca` exists

**Comment by paolochiodi** [comment]
Maybe it is worth checking with seneca "core" if the dropping of `seneca` was intentional or not?

cc @mcdonnelldean ☝️

**Comment by marcopiraccini** [comment]
Fixed testing only the presence of the "level" attribute: https://github.com/senecajs/seneca-in-practice/blob/master/problems/comparestdout-filterlogs.js#L17

**Comment by marcopiraccini** [comment]
@paolochiodi can you pleas check if now the desc are clearer? https://github.com/senecajs/seneca-in-practice/pull/64
