### ISSUE TITLE
Review patterns in examples

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#63]
Patterns can be expressed as objects and as strings. 
In proposed solutions, all are (now) expressed as objects. We should review problem descriptions to have this coherent.

**Comment by piccoloaiutante** [comment]
PR pending https://github.com/senecajs/seneca-in-practice/pull/66

**Comment by marcopiraccini** [comment]
Merged, but not closing because a couple of proposed solutions are still using strings :)

**Comment by piccoloaiutante** [comment]
https://github.com/senecajs/seneca-in-practice/commit/711d1e79219695f2f8d67ec684484bb67450bae8

Anything else @marcopiraccini ?

**Comment by marcopiraccini** [comment]
Yes, please, here: https://github.com/senecajs/seneca-in-practice/blob/master/problems/prior_actions/solution/solution.js and: https://github.com/senecajs/seneca-in-practice/blob/master/problems/plugin/solution/solution.js :)

**Comment by piccoloaiutante** [comment]
there you go :) 

https://github.com/senecajs/seneca-in-practice/pull/67
