### ISSUE TITLE
Incorrect markdown rendering in CLI

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-in-practice#73]
In console the rendering of the markdown in the "Override" lesson seems to miss some spaces. Github renders them correctly.

Console screenshot:
![override](https://cloud.githubusercontent.com/assets/4950500/19038035/49b4b1de-8982-11e6-8b49-766af1ee46f6.png)

**Comment by marcopiraccini** [comment]
Seems harder to fix than expected :D

**Comment by mihaidma** [comment]
yes :) I also did a quick try.
