### ISSUE TITLE
seneca-mem-store readme sample needs update

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-in-practice#77]
you have to call `use(basic)` to make it work:

```
   var seneca = require('seneca')()
    seneca.use('basic')
    seneca.use('entity')
```

**Comment by marcopiraccini** [comment]
Yes, but it's not required for the solution. Do you mean that we should specify that in the description?

**Comment by mihaidma** [comment]
Indeed it is no necessary to build the solution. But if you try to run the sample from Readme it won't work.

**Comment by marcopiraccini** [comment]
https://github.com/senecajs/seneca-in-practice/pull/80
