### ISSUE TITLE
Avoid in the "sum" solution to export seneca

### ISSUE THREAD

**Issue by marcopiraccini** [senecajs/seneca-in-practice#9]
Currently the "sum" solution needs seneca to be exported:

```
var seneca = require('seneca')()
seneca.add({role: 'math', cmd: 'sum'}, function (msg, respond) {
  var sum = msg.left + msg.right
  respond(null, {answer: sum})
})
module.exports = seneca
```

This is needed because the `seneca-sum-executor` requires it and in that way it has the same seneca on which call "act" to verify the solution. 
We should find another way of testing the solution to avoid that, since it can be confusing (even if in the exercise text is specified the purpose of the export).

**Comment by piccoloaiutante** [comment]
Is it still relevant @marcopiraccini ?

**Comment by marcopiraccini** [comment]
Yes! :)

**Comment by marcopiraccini** [comment]
Closing, not good alternative found....
